name: Build and Push Docker Images

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push Web App
        run: |
          ECR="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com"
          docker build -t clo835-webapp ./app
          docker tag clo835-webapp:latest $ECR/clo835-webapp:latest
          docker tag clo835-webapp:latest $ECR/clo835-webapp:${{ github.sha }}
          docker push $ECR/clo835-webapp:latest
          docker push $ECR/clo835-webapp:${{ github.sha }}

      - name: Build & Push MySQL
        run: |
          ECR="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com"
          docker build -t clo835-mysql ./mysql
          docker tag clo835-mysql:latest $ECR/clo835-mysql:latest
          docker tag clo835-mysql:latest $ECR/clo835-mysql:${{ github.sha }}
          docker push $ECR/clo835-mysql:latest
          docker push $ECR/clo835-mysql:${{ github.sha }}
